Use vector::reserve()
reMarkable/depixelator pull request #4
Opened 2020-08-31 13:52 UTC by Waqar144

2020-08-31 20:20 UTC, sandsmark commented
lgtm, but I'll let gunnar have the final word

2020-09-01 04:28 UTC, sletta requested changes
Hi and thanks for contributing to depixelator!

Doing this for the Polylines overloads makes complete sense :)

For the various other cases as the input is unknown, that makes picking default sizes more or less pure guesswork :) So in general, I would prefer defaulting to lower values and allow for reallocs on demand, rather than always over-allocating.

2020-09-01 04:28 UTC, sletta commented on depixelator.h
> +    segments.reserve( (xsteps * ysteps) / 3);
What is the rationale for just this number?

2020-09-01 04:28 UTC, sletta commented on depixelator.h
> +    polyline.reserve(segments.size());
The polyline will only grow this large if we have a single contour in the entire scene which will almost never be the case, so I think this is allocating a bit to excessively. Also, given that we grow and clear repeatedly below, the benefit of resizing this thing ahead of time will only marginally benefit us..

2020-09-01 04:28 UTC, sletta commented on depixelator.h
> +    result.reserve(polyline.size() / 2);
Why half? Chances are we discard a lot of points so I'd aim for lower by default unless there is a mathematical argument for 1/2?

2020-09-01 04:28 UTC, sletta commented on depixelator.h
> +    result.reserve(polyline.size());
This adds 3 points per input point on average so to be useful it should be `polyline.size() * 3`

2020-09-01 04:28 UTC, sletta commented on depixelator.h
> +    result.reserve(polyline.size());
Slope tracing is expected to reduce a lot of points, so if anything, we should reserve only a fraction of the input.

2020-09-01 09:35 UTC, Waqar144 commented on depixelator.h
> +    segments.reserve( (xsteps * ysteps) / 3);
There is no concrete rational and I think there can't be. I just tested with a few images and the value was usually close to / around, one third of `xsteps * ysteps`. However, it can even be double that or half or any other number (depending upon the `mask` value. So yeah, this is just guesswork.

2020-09-01 09:41 UTC, Waqar144 commented on depixelator.h
> +    polyline.reserve(segments.size());
True. However `clear()` will retain the memory we reserved so, wouldn't it still be useful?

2020-09-01 09:56 UTC, Waqar144 commented on depixelator.h
> +    result.reserve(polyline.size() / 2);
What do you suggest?

2020-09-01 09:56 UTC, Waqar144 commented on depixelator.h
> +    result.reserve(polyline.size());
What do you suggest?

2020-09-02 04:52 UTC, sletta commented on depixelator.h
> +    polyline.reserve(segments.size());
My point is it is far to large given that we'll typically have 1000s of lines in an image, so the memory is wasted.

2020-09-02 04:56 UTC, sletta commented on depixelator.h
> +    segments.reserve( (xsteps * ysteps) / 3);
ok, lets go with this then :)

2020-09-02 04:57 UTC, sletta commented on depixelator.h
> +    result.reserve(polyline.size());
Something very conservative :) 1/10 of the input points perhaps?

2020-09-02 04:58 UTC, sletta commented on depixelator.h
> +    result.reserve(polyline.size() / 2);
Something conservative again.. 1/10 perhaps?

2020-09-02 14:41 UTC, Waqar144 commented
Updated with requested changes.

2020-09-03 06:25 UTC, sletta approved these changes

2020-09-03 06:25 UTC, merged